#!/usr/bin/env bash
set -euo pipefail

DATA_DIR="${DATA_DIR:-/home/${USER}/naturavision-data}"
OUTPUT_ROOT="${OUTPUT_ROOT:-/home/${USER}/runs-canary-wsl}"
STAGE1_MAX_STEPS="${STAGE1_MAX_STEPS:--1}"
STAGE2_MAX_STEPS="${STAGE2_MAX_STEPS:-200}"
STAGE1_EPOCHS="${STAGE1_EPOCHS:-1}"
STAGE2_EPOCHS="${STAGE2_EPOCHS:-1}"
TRAIN_BATCH_SIZE="${TRAIN_BATCH_SIZE:-1}"
EVAL_BATCH_SIZE="${EVAL_BATCH_SIZE:-1}"
GRAD_ACCUM_STEPS="${GRAD_ACCUM_STEPS:-32}"
EVAL_STEPS="${EVAL_STEPS:-25}"
SAVE_STEPS="${SAVE_STEPS:-25}"

export DATA_DIR OUTPUT_ROOT STAGE1_MAX_STEPS STAGE2_MAX_STEPS
export STAGE1_EPOCHS STAGE2_EPOCHS TRAIN_BATCH_SIZE EVAL_BATCH_SIZE
export GRAD_ACCUM_STEPS EVAL_STEPS SAVE_STEPS

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
"${SCRIPT_DIR}/train_qwen35_4b_qlora_wsl.sh"
